apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hello-kubernetes
  source:
    repoURL: "<YOUR_REGISTRY>/helm-charts"
    chart: hello-kubernetes
    targetRevision: "1.0.0"
    plugin:
      name: argocd-oci-plugin-helm
      env:
      - name: AOP_REPOSITORY
        value: <YOUR_REGISTRY>/values/hello-kubernetes-values
      - name: AOP_TAG
        value: v2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
